import java.security.PublicKey;

public class Main {
    public static void main(String[] args) {

        //Arthmetic_Operations.

        int x = 5;
        int y = 10;
        System.out.println(x+y);  // Addition of two variables

        int x1 = 10;
        int y1 = 20;
        System.out.println(x1-y1);

        int x2 = 10;
        int y2 = 5;
        System.out.println(x2/y2); // it retursn the value of quoishent

        int x3 = 10;
        int y3 = 5;
        System.out.println(x3%y3); // it returns the value of Reminder

        int x4 = 10;
        x4+= 5; //addition assignment operator (+=) adds a value to a variable

        System.out.println(x4);
    }
}


